version: "3.8"

services:
  erpnext:
    image: frappe/erpnext:v15
    container_name: erpnext_test
    ports:
      - "8000:8000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    command: >
      bash -c "
      if [ ! -d sites/test.local ]; then
        bench new-site test.local
        --admin-password admin
        --db-root-password root;
        bench --site test.local install-app erpnext;
        bench --site test.local install-app education;
      fi;
      bench start
      "

volumes:
  sites:
